### ISSUE TITLE
setNodeData() seems to be lazy

### ISSUE THREAD

**Issue by avanc** [Homegear/libhomegear-node#1]
I have the following function node:

    setNodeData($inputIndex, $message['payload']);
    $tmp=getNodeData(0);
    $msg=[];
    $msg['payload']=$tmp;
    return $msg;

It seems that getNode() gets the previous value and not the current.

1. true -> false
2. true -> true
3. true -> true
4. false -> true
5. false -> false
6. true -> false
7. true -> true

I'm currently using homegear 0.7.30.

Besides: How can I export a flow to paste it here?

**Comment by hfedcba** [comment]
Hi @avanc,

you can export the flow from the Node-BLUE menu.

The reason why this doesn't work is, that the data is written asynchronously to the database. So `setNodeData()` is not finished yet when you call `getNodeData()` immediately afterwards. To get the data immediately it would need to be cached and that might take a lot of memory - depending on the stored data. So this is expected behaviour. I'm open to suggestions though, if that causes problems.

Cheers,

Sathya

**Comment by avanc** [comment]
Thanks for the hint.

Does this mean that I never now for sure if the getNodeData() is the latest? How about the next time the flow is running? Or if a message arrives almost parallel?

My current flow looks like: [flow.txt](https://github.com/Homegear/libhomegear-node/files/3035480/flow.txt)
What happens if Türkontakt and Keymatic fire at almost the same time?

Is it possible to add an optional boolean in setNodeData()to mark the function as synchronous/blocking? Or force a flush for storing data in getNodeData()?

**Comment by hfedcba** [comment]
Hi @avanc,

I'm looking into it right now and: I already cache the values. So actually your example should work. Might have something to do with PHP...

Cheers,

Sathya

**Comment by hfedcba** [comment]
Problem found and it works now :-) - The PHP functions did not wait for a reply. Now they do. Thank you!

**Comment by avanc** [comment]
Great!
Solved in https://github.com/Homegear/Homegear/commit/7b03791d77ba1f77c8c3b8a1555dca36f28e1dae (just a reference to check when it arrives on my system).
